# Generated by Django 6.0 on 2026-01-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
