# Generated by Django 6.0 on 2026-01-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcategories', '0001_initial'),
        ('products', '0002_product_dimensions_product_meta_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='productcategories.category'),
        ),
    ]
