# Generated by Django 6.0 on 2026-01-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_old',
            field=models.CharField(db_column='category', default='', max_length=255),
            preserve_default=False,
        ),
    ]
