# Generated by Django 6.0 on 2026-01-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_category_product_category_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_old',
        ),
    ]
